#!/usr/bin/python
#
# Florin Papa <florin.papa@intel.com>
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

import sys
import parser
import optparse
import os

# input file
URLS_TEMPLATE = "urls_template.txt"
URLS_OUT = "urls.txt"


def parse_urls():
    has_error = False

    with open(URLS_OUT, 'w') as url_file:
        with open(URLS_TEMPLATE) as url_template_file:
            for line in url_template_file:
                line = line.strip()
                parts = line.split()
                if (len(parts) != 2):
                    print ("ERROR: Invalid format for " + URLS_TEMPLATE + " file\n"
                           "Use the -h option of this program for instructions\n")
                    has_error = True
                    break
                repeat = 1
                try:
                    repeat = int(parts[1])
                except ValueError:
                    print ("ERROR: Weight number in " + URLS_TEMPLATE + " file"
                           " is not an int\n")
                    has_error = True
                    break
                while (repeat > 0):
                    url_file.write(parts[0] + "\n")
                    repeat = repeat - 1

    if has_error:
        os.remove(URLS_OUT)
        sys.exit()
    else:
        print ("File " + URLS_OUT + " generated successfully\n")


def main(argv):
    optparse.OptionParser.format_epilog = lambda self, formatter: self.epilog
    parser = optparse.OptionParser(
        usage = "./%prog",
        epilog =
"""
Parse urls_template.txt file to obtain the urls.txt
input file for Siege. The format of the
urls_template.txt file is as follows:

http://host:port/page1 w1
http://host:port/page2 w2
http://host:port/page3 w3

where w is the weight of that page, expressed as an
integer. This way, page1 will be acccessed by siege
roughly w1 / (w1 + w2 + w3) of the total requests
""")


    options, args = parser.parse_args(argv)
    if len(args) != 0:
        parser.error("This program takes no arguments")

    parse_urls()


if __name__ == "__main__":
    main(sys.argv[1:])
